rollout DynamicProjection "Dynamic Projection"
(
    label   lb_FileName   "File Name" pos:[20,15]
    spinner spin_Radius   "Radius" type:#integer range:[250,600, 250] pos:[43,45] width:70
    button  btn_Left      "Left" pos:[120,42] width:60
	button  btn_Right     "Right" pos:[190,42] width:60
	button  btn_Export   "Export" pos:[270,13] width:110 height:50
)

createdialog DynamicProjection width:400 height:75